name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ To the person (who assigned me this fantastic coding challenge),"
      - run: echo "ğŸ§ Greetings and hope you are doing great !"
      - run: echo "ğŸ§ Your assignment has given me couple of sleep less nights ! I have only done some part of it."
      - run: echo "ğŸ§ I have tried my best to solve this but i understood that my current skills are not enough to complete it !"
      - run: echo "ğŸ§ But iam sure, if given a chance, i will upgrade my skills on the job and by demand, "
      - run: echo "ğŸ§ since i got the feel of the CI/CD space and i really like to work on it & to be challenged. "
      - run: echo "ğŸ§ I hope you have assessed me by now :) "
      - run: echo " "
      - run: echo "ğŸ§ Yours Sincerely,"
      - run: echo "ğŸ§ Prasanth"
	  
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
